Title
========================================================
```{r workset up, echo=FALSE}
opts_chunk$set(tidy=FALSE,cache.path="./cache/")
```
Synopsis:

Data Processing
```{r data input, cache=TRUE}
data <- read.csv("data/repdata-data-StormData.csv.bz2",
                 stringsAsFactors = FALSE)
```
```{r cleaning data, cache=TRUE}
names(data) <- tolower(names(data))
data$bgn_date <- as.Date(data$bgn_date,  "%m/%d/%Y")
data$evtype <- as.factor(data$evtype)
data <- cbind(data,
              data.frame(health = apply(subset(data, select = c(fatalities,
                                                                injuries)),
                                        1,
                                        sum)
              )
)

# make propdmgexp usable
data$propdmgexp <- sub("h", "2", data$propdmgexp, ignore.case = TRUE)
data$propdmgexp <- sub("k", "3", data$propdmgexp, ignore.case = TRUE)
data$propdmgexp <- sub("m", "6", data$propdmgexp, ignore.case = TRUE)
data$propdmgexp <- sub("b", "9", data$propdmgexp, ignore.case = TRUE)
# deal with unknown variables.
data$propdmgexp <- sub("-", "0", data$propdmgexp)
data$propdmgexp <- sub("\\?","0",data$propdmgexp)
data$propdmgexp <- sub("\\+", "0", data$propdmgexp)
data$propdmgexp <- sub("","0", data$propdmgexp)
# convert to a numeric
data$propdmgexp <- as.numeric(data$propdmgexp)
#
# make cropdmgexp usable
#
data$cropdmgexp <- sub("h", "2", data$cropdmgexp, ignore.case = TRUE)
data$cropdmgexp <- sub("k", "3", data$cropdmgexp, ignore.case = TRUE)
data$cropdmgexp <- sub("m", "6", data$cropdmgexp, ignore.case = TRUE)
data$cropdmgexp <- sub("b", "9", data$cropdmgexp, ignore.case = TRUE)
# deal with unknown variables.
data$cropdmgexp <- sub("-"  , "0", data$cropdmgexp)
data$cropdmgexp <- sub("\\+", "0", data$cropdmgexp)
data$cropdmgexp <- sub("\\?", "0", data$cropdmgexp)
data$cropdmgexp <- sub(""   , "0", data$cropdmgexp)
# convert to a numeric
data$cropdmgexp <- as.numeric(data$cropdmgexp)
#
# compute total prop and crop damages the total financial loss report for each event
#

temp <- data$propdmg * (10 ^ data$propdmgexp)
data <- cbind(data,
              data.frame(propcash = temp))
temp <- data$cropdmg * (10 ^ data$cropdmgexp)
data <- cbind(data,
              data.frame(cropcash = temp))
temp <- data$propcash + data$cropcash
data <- cbind(data,
              data.frame(totalcash = temp))
rm(temp)
```

```{r more cleaning, cache=TRUE}
levels(data$evtype)[levels(data$evtype) == "blowing snow"] <- "BLOWING SNOW"
levels(data$evtype)[levels(data$evtype) == "Coastal Flooding"] <- "COASTAL FLOOD"
levels(data$evtype)[levels(data$evtype) == "COASTAL FLOODING"] <- "COASTAL FLOOD"
levels(data$evtype)[levels(data$evtype) == "COASTAL FLOODING/EROSION"] <- "COASTAL FLOOD"
levels(data$evtype)[levels(data$evtype) == "COASTAL STORM"] <- "COASTAL STORM"
levels(data$evtype)[levels(data$evtype) == "Coastal Storm"] <- "COASTAL STORM"
levels(data$evtype)[levels(data$evtype) == "COASTALSTORM"] <- "COASTAL STORM"
levels(data$evtype)[levels(data$evtype) == "COLD AND SNOW"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "Cold Temperature"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "COLD WAVE"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "COLD WEATHER"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "COLD/WIND CHILL"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "COLD/WINDS"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "DROUGHT/EXCESSIVE HEAT"] <- "EXCESSIVE HEAT"
levels(data$evtype)[levels(data$evtype) == "DRY MIRCOBURST WINDS"] <- "DRY MIRCOBURST"
levels(data$evtype)[levels(data$evtype) == "Dust Devil"] <- "DUST DEVIL"
levels(data$evtype)[levels(data$evtype) == "Extended Cold"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "Extreme Cold"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "EXTREME COLD/WIND CHILL"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "EXTREME WINDCHILL"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "FLASH FLOOD/FLOOD"] <- "FLASH FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLASH FLOODING"] <- "FLASH FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLASH FLOODING/FLOOD"] <- "FLASH FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLASH FLOODS"] <- "FLASH FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLOOD & HEAVY RAIN"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLOOD/FLASH FLOOD"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLOOD/RIVER FLOOD"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "FLOODING"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "FOG AND COLD TEMPERATURES"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "FREEZING RAIN/SNOW"] <- "FREEZING RAIN"
levels(data$evtype)[levels(data$evtype) == "Freezing Spray"] <- "FREEZING SPRAY"
levels(data$evtype)[levels(data$evtype) == "GLAZE/ICE STORM"] <- "ICE STORM"
levels(data$evtype)[levels(data$evtype) == "GUSTY WIND"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "GUSTY WINDS"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "Gusty winds"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "Gusty Winds"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "HEAT WAVE"] <- "HEAT"
levels(data$evtype)[levels(data$evtype) == "Heat Wave"] <- "HEAT"
levels(data$evtype)[levels(data$evtype) == "HEAT WAVE DROUGHT"] <- "HEAT"
levels(data$evtype)[levels(data$evtype) == "HEAT WAVES"] <- "HEAT"
levels(data$evtype)[levels(data$evtype) == "HEAVY RAINS"] <- "HEAVY RAIN"
levels(data$evtype)[levels(data$evtype) == "HEAVY SNOW"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "HEAVY SNOW AND HIGH WINDS"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "Heavy snow shower"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "HEAVY SNOW/BLIZZARD/AVALANCHE"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "HEAVY SNOW/ICE"] <- " SNOW"
levels(data$evtype)[levels(data$evtype) == "Heavy Surf"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "Heavy surf and wind"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "HEAVY SURF/HIGH SURF"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "HIGH"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH SURF"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "High Surf"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "HIGH SWELLS"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "HIGH WIND 48"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WIND AND SEAS"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WIND/HEAVY SNOW"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WIND/SEAS"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WINDS"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WINDS/COLD"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "HIGH WINDS/SNOW"] <- "HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "Hurricane Edouard"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE EMILY"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE ERIN"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE FELIX"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE OPAL"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE OPAL/HIGH WINDS"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE/TYPHOON"] <- "HURRICANE"
levels(data$evtype)[levels(data$evtype) == "HURRICANE-GENERATED SWELLS"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "HYPOTHERMIA"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "Hypothermia/Exposure"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "HYPOTHERMIA/EXPOSURE"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "ICE ON ROAD"] <- "ICE"
levels(data$evtype)[levels(data$evtype) == "ICE ROADS"] <- "ICE"
levels(data$evtype)[levels(data$evtype) == "ICE STORM"] <- "ICE"
levels(data$evtype)[levels(data$evtype) == "ICE STORM/FLASH FLOOD"] <- "ICE"
levels(data$evtype)[levels(data$evtype) == "ICY ROADS"] <- "ICE"
levels(data$evtype)[levels(data$evtype) == "LANDSLIDES"] <- "LANDSLIDE"
levels(data$evtype)[levels(data$evtype) == "LIGHT SNOW"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "LIGHTNING AND THUNDERSTORM WIN AVALANCHE"] <- "THUNDERSTORM"
levels(data$evtype)[levels(data$evtype) == "LIGHTNING INJURY"] <- "LIGHTNING"
levels(data$evtype)[levels(data$evtype) == "LIGHTNING."] <- "LIGHTNING"
levels(data$evtype)[levels(data$evtype) == "LOW TEMPERATURE"] <- "COLD"
levels(data$evtype)[levels(data$evtype) == "MARINE MISHAP"] <- "MARINE ACCIDENT"
levels(data$evtype)[levels(data$evtype) == "MARINE STRONG WIND"] <- "MARINE HIGH WIND"
levels(data$evtype)[levels(data$evtype) == "MARINE THUNDERSTORM WIND"] <- "MARINE THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "MARINE TSTM WIND"] <- "MARINE THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "MINOR FLOODING"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "Mudslide"] <- "MUDSLIDE"
levels(data$evtype)[levels(data$evtype) == "Mudslides"] <- "MUDSLIDE"
levels(data$evtype)[levels(data$evtype) == "NON TSTM WIND"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "NON-SEVERE WIND DAMAGE"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "RAIN/SNOW"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "RAIN/WIND"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "RAPIDLY RISING WATER"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "RECORD COLD"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "RECORD HEAT"] <- "EXTREME HEAT"
levels(data$evtype)[levels(data$evtype) == "RECORD/EXCESSIVE HEAT"] <- "EXTREME HEAT"
levels(data$evtype)[levels(data$evtype) == "RIP CURRENTS"] <- "RIP CURRENT"
levels(data$evtype)[levels(data$evtype) == "RIP CURRENTS/HEAVY SURF"] <- "RIP CURRENT"
levels(data$evtype)[levels(data$evtype) == "RIVER FLOOD"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "RIVER FLOODING"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "River Flooding"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "ROUGH SEAS"] <- "HIGH SEAS"
levels(data$evtype)[levels(data$evtype) == "ROUGH SURF"] <- "HEAVY SURF"
levels(data$evtype)[levels(data$evtype) == "SMALL HAIL"] <- "HAIL"
levels(data$evtype)[levels(data$evtype) == "Snow"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "SNOW AND ICE"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "SNOW SQUALL"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "Snow Squalls"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "SNOW/ BITTER COLD"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "SNOW/HIGH WINDS"] <- "SNOW"
levels(data$evtype)[levels(data$evtype) == "STORM SURGE/TIDE"] <- "STORM SURGE"
levels(data$evtype)[levels(data$evtype) == "STRONG WINDS"] <- "STRONG WIND"
levels(data$evtype)[levels(data$evtype) == "Strong Winds"] <- "STRONG WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WIND (G40)"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WIND G52"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WINDS"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WINDS 13"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WINDS/HAIL"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORM WINDSS"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORMS WINDS"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERSTORMW"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "THUNDERTORM WINDS"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "TORNADO F2"] <- "TORNADO"
levels(data$evtype)[levels(data$evtype) == "TORNADO F3"] <- "TORNADO"
levels(data$evtype)[levels(data$evtype) == "TORNADOES, TSTM WIND, HAIL"] <- "TORNADO"
levels(data$evtype)[levels(data$evtype) == "Torrential Rainfall"] <- "RAIN"
levels(data$evtype)[levels(data$evtype) == "TROPICAL STORM GORDON"] <- "TROPICAL STORM"
levels(data$evtype)[levels(data$evtype) == "TSTM WIND"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "TSTM WIND (G35)"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "TSTM WIND (G40)"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "TSTM WIND (G45)"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "TSTM WIND/HAIL"] <- "THUNDERSTORM WIND"
levels(data$evtype)[levels(data$evtype) == "UNSEASONABLY COLD"] <- "EXTREME COLD"
levels(data$evtype)[levels(data$evtype) == "UNSEASONABLY WARM"] <- "EXTREME HEAT"
levels(data$evtype)[levels(data$evtype) == "UNSEASONABLY WARM AND DRY"] <- "EXTREME HEAT"
levels(data$evtype)[levels(data$evtype) == "URBAN AND SMALL STREAM FLOODIN FREEZE"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "URBAN/SML STREAM FLD"] <- "FLOOD"
levels(data$evtype)[levels(data$evtype) == "WARM WEATHER"] <- "EXTREME HEAT"
levels(data$evtype)[levels(data$evtype) == "WATERSPOUT TORNADO"] <- "WATERSPOUT"
levels(data$evtype)[levels(data$evtype) == "WATERSPOUT/TORNADO"] <- "WATERSPOUT"
levels(data$evtype)[levels(data$evtype) == "Whirlwind"] <- "WHIRLWIND"
levels(data$evtype)[levels(data$evtype) == "WILD FIRES"] <- "WILD FOREST FIRE"
levels(data$evtype)[levels(data$evtype) == "WILDFIRE"] <- "WILD FOREST FIRE"
levels(data$evtype)[levels(data$evtype) == "WIND STORM"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "WINDS"] <- "WIND"
levels(data$evtype)[levels(data$evtype) == "WINTER STORM HIGH WINDS"] <- "WINTER STORM"
levels(data$evtype)[levels(data$evtype) == "WINTER STORMS"] <- "WINTER STORM"
levels(data$evtype)[levels(data$evtype) == "WINTER WEATHER MIX"] <- "WINTER WEATHER"
levels(data$evtype)[levels(data$evtype) == "WINTER WEATHER/MIX"] <- "WINTER WEATHER"
levels(data$evtype)[levels(data$evtype) == "WINTRY MIX"] <- "WINTER WEATHER"

```


```{r building working data, cache=TRUE}
health.impact <- subset(data, 
                        ((health >0) & (bgn_date > as.Date("1991-01-01", "%Y-%m-%d"))),
                         select=c(bgn_date,evtype,health))
financial.impact  <- subset(data, 
                            ((totalcash > 0) & (bgn_date > as.Date("1991-01-01", "%Y-%m-%d"))),
                            select = c(bgn_date, evtype, propcash, cropcash, totalcash))
```


Results

